name: projet_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  shimmer: ^2.0.0


dependencies:

  flutter:
    sdk: flutter
  flutter_map:
    path: ./leaflet
  location: ^4.1.1
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fancy_bottom_navigation:  
  hexcolor: ^2.0.5
  pedantic: ^1.11.0

flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/map/anholt_osmbright/12/2177/
    - assets/map/anholt_osmbright/12/2178/
    - assets/map/anholt_osmbright/12/2179/
    - assets/map/anholt_osmbright/12/2180/
    - assets/map/anholt_osmbright/12/2181/
    - assets/map/anholt_osmbright/13/4354/
    - assets/map/anholt_osmbright/13/4355/
    - assets/map/anholt_osmbright/13/4356/
    - assets/map/anholt_osmbright/13/4357/
    - assets/map/anholt_osmbright/13/4358/
    - assets/map/anholt_osmbright/13/4359/
    - assets/map/anholt_osmbright/13/4360/
    - assets/map/anholt_osmbright/13/4361/
    - assets/map/anholt_osmbright/13/4362/
    - assets/map/anholt_osmbright/13/4363/
    - assets/map/anholt_osmbright/14/8709/
    - assets/map/anholt_osmbright/14/8710/
    - assets/map/anholt_osmbright/14/8711/
    - assets/map/anholt_osmbright/14/8712/
    - assets/map/anholt_osmbright/14/8713/
    - assets/map/anholt_osmbright/14/8714/
    - assets/map/anholt_osmbright/14/8715/
    - assets/map/anholt_osmbright/14/8716/
    - assets/map/anholt_osmbright/14/8717/
    - assets/map/anholt_osmbright/14/8718/
    - assets/map/anholt_osmbright/14/8719/
    - assets/map/anholt_osmbright/14/8720/
    - assets/map/anholt_osmbright/14/8721/
    - assets/map/anholt_osmbright/14/8722/
    - assets/map/anholt_osmbright/14/8723/
    - assets/map/anholt_osmbright/14/8724/
    - assets/map/anholt_osmbright/14/8725/
    - assets/map/anholt_osmbright/14/8726/
    - assets/map/anholt_osmbright/14/8727/
